config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index"

  post "tasks", to: "tasks#create"
  get "/tasks/new", to: "tasks#new", as: :new_task

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task


  patch "/tasks/:id", to: "tasks#update"

  delete "/tasks/:id", to: "tasks#destroy"
  get "/tasks/:id", to: "tasks#show", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task_id, only:[:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task_id
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>


<i class="fas fa-undo"><%= link_to "Back to list", "/tasks" %></i>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <% if task.completed == false %>
      <li><i class="far fa-square"></i><%= link_to task.title, task_path(task) %> .<i class="far fa-trash-alt"></i></li>
    <% else %>
      <li><i class="far fa-check-square"></i><%= link_to task.title, task_path(task) %> .<i class="far fa-trash-alt"></i></li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Add a new task", "/tasks/new" %>

app/views/tasks/new.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<i class="fas fa-undo"><%= link_to "Back to list", "/tasks" %></i>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<% if @task.completed == false %>
  <p><i class="far fa-square"></i><%= @task.completed %></p>
<% else %>
  <p><i class="far fa-check-square"></i><%= @task.completed %></p>
<% end %>

<i class="fas fa-undo"><%= link_to "back to list", "/tasks" %></i>
<i class="fas fa-wrench"><%= link_to "Edit the task", edit_task_path(@task) %></i>

<%= link_to task_path(@task), method: :delete, data: { confirm: "Are you sure?" } do %>
  <i class="far fa-trash-alt"></i>
<% end %>